// Source of truth mapping raw Drive files -> portfolio entries.
// `brand: null` means the clip could not be attributed from its frame; copy stays
// descriptive and must never imply a client relationship we haven't confirmed.
export const RAW_DIR = '/Users/alex.flowers/Desktop/autumns-site/raw-assets';

export const CATEGORIES = [
  { id: 'markets', label: 'Local Markets & Retail' },
  { id: 'homes', label: 'Home & Real Estate' },
  { id: 'tourism', label: 'Tourism & Outdoors' },
  { id: 'food', label: 'Restaurants & Food' },
  { id: 'beauty', label: 'Beauty & Wellness' },
  { id: 'family', label: 'Family Brands' },
  { id: 'events', label: 'Events & Hospitality' },
];

export const ITEMS = [
  { file: 'STG MAMA INTRO.mp4', slug: 'stg-mama-intro', hero: true, brand: null,
    title: 'Meet St. George Mama', cat: 'events',
    desc: 'The introduction reel — a run through the local businesses, markets and desert mornings that make up the St. George Mama beat.' },

  // --- Local markets & retail ---
  { file: 'Vintage Market Days.MP4', slug: 'vintage-market-days', brand: 'Vintage Market Days',
    title: 'Vintage Market Days', cat: 'markets',
    desc: 'A wander through the stalls — handmade bookmarks, stacked vintage books, bunting overhead. Shot to feel like you are walking it yourself.' },
  { file: 'The Mod Market.mp4', slug: 'the-mod-market', brand: 'The Mod Market',
    title: 'The Mod Market', cat: 'markets',
    desc: 'A full wall of earrings, shot close and moving slowly so every pair reads before the cut.' },
  { file: 'The Mathis Market.MP4', slug: 'the-mathis-market', brand: 'The Mathis Market',
    title: 'The Mathis Market', cat: 'markets',
    desc: 'Vendor booths under string lights, colour-led cuts that carry the browsing rhythm of the market.' },
  { file: 'The Spring Market-28-2025 21-45-51_1.MP4', slug: 'the-spring-market', brand: 'The Spring Market',
    title: 'The Spring Market', cat: 'markets',
    desc: 'Permanent jewelry and piercings at the spring pop-up, with the signage given room to land.' },
  { file: 'Chained and Charmed.MOV', slug: 'chained-and-charmed', brand: 'Chained & Charmed',
    title: 'Chained & Charmed', cat: 'markets',
    desc: 'Permanent jewelry, welded on the spot. Tight focus on hands and chain so the craft is the story.' },
  { file: 'Krazy K Maks.MP4', slug: 'krazy-k-maks', brand: 'Krazy K Maks',
    title: 'Krazy K Maks', cat: 'markets',
    desc: 'Reaching into the case for the pick of the day — shot handheld and close for that first-person pull.' },
  { file: 'DT FARMERS.MOV', slug: 'downtown-farmers-market', brand: 'Downtown Farmers Market',
    title: 'Downtown Farmers Market', cat: 'markets',
    desc: 'Iced and decorated cookies laid out on the tray, framed so the colour does the selling.' },
  { file: '696C479D-044D-4DC1-9576-AD7BB1FB9DAA.MP4', slug: 'jewelry-booth', brand: null,
    title: 'Handmade jewelry booth', cat: 'markets',
    desc: 'A maker\'s table styled end to end — trays of stones, hanging pairs, everything catching the daylight.' },
  { file: 'CF71B848-B37D-46C5-A0F6-77252B5F4F27.MP4', slug: 'indoor-market-hall', brand: null,
    title: 'Market hall walkthrough', cat: 'markets',
    desc: 'Following the aisle through a covered market — a walking shot that lets the scale of the room register.' },
  { file: '19EB11DE-1528-4381-B82D-413EE861CB8D.MP4', slug: 'market-drink', brand: null,
    title: 'Market day, first sip', cat: 'markets',
    desc: 'Nine seconds, one beat: the drink, the grin, the green tents behind. Built for a story frame.' },
  { file: 'E25A03E7-FE4D-433D-BB2F-482772206AE7.MP4', slug: 'disco-hat', brand: null,
    title: 'Statement piece', cat: 'markets',
    desc: 'A mirrored cowboy hat throwing light around the room — shot to make one object the whole reel.' },
  { file: 'EFCA4F37-3003-4420-A240-0A93C72F6AB5.MP4', slug: 'frame-styling', brand: null,
    title: 'Styling on chevron oak', cat: 'markets',
    desc: 'Flat-lay staging on a herringbone table, product moved into frame by hand rather than cut to.' },
  { file: 'A64A3CB0-24FF-4ECB-B3A5-AB05E6D5BEEB.MP4', slug: 'soap-demo', brand: null,
    title: 'In-use product demo', cat: 'markets',
    desc: 'Hands, water, lather — the everyday-use shot brands ask for, kept unglamorous on purpose.' },

  // --- Home & real estate ---
  { file: 'Summit View Cedar Pointe Homes Reel.MP4', slug: 'summit-view-cedar-pointe', brand: 'Summit View / Cedar Pointe Homes',
    title: 'Summit View at Cedar Pointe', cat: 'homes',
    desc: 'Interiors walked slowly and evenly — canopy bed, fan turning, light held long enough to sell the room.' },
  { file: 'IH Dec Wk 3 Reel 1.mp4', slug: 'model-home-walkthrough', brand: null,
    title: 'Model home walkthrough', cat: 'homes',
    desc: 'A walking tour of a near-finished build, paced so each room lands before the next.' },
  { file: '9A8ED1C8-4EFB-4C3A-A007-A1229D9CB2DB.MP4', slug: 'new-build-dusk', brand: null,
    title: 'New build at dusk', cat: 'homes',
    desc: 'Golden hour on a finished exterior, warm windows against a cooling sky.' },
  { file: '5AD2B0B3-7334-47AF-9DBE-813972006739.MP4', slug: 'framing-walkthrough', brand: null,
    title: 'Framing stage walkthrough', cat: 'homes',
    desc: 'Open studs and bare subfloor — the in-progress footage builders use to show work underway.' },
  { file: 'BE5BEBA0-00ED-4979-B388-EF190B047868.MP4', slug: 'commercial-exterior', brand: null,
    title: 'Commercial exterior', cat: 'homes',
    desc: 'Clean architectural lines shot against desert sky, framed for a wide crop.' },
  { file: '3A412932-B7B8-463A-B5EF-6A979CDB6CF6.MP4', slug: 'tiled-shower', brand: null,
    title: 'Tile & fixture detail', cat: 'homes',
    desc: 'Glass, tile and running water — a finish-detail shot for a build or fixture brand.' },
  { file: 'ESolar Client Review.MOV', slug: 'esolar-client-review', brand: null,
    title: 'Rooftop solar install', cat: 'homes',
    desc: 'Panels on a finished roof with a spoken client review over the top — proof-of-work content for a home services install.' },

  // --- Tourism & outdoors ---
  { file: 'Pete Vortex.MP4', slug: 'red-rock-aerial', brand: null,
    title: 'Red rock, from the air', cat: 'tourism',
    desc: 'FPV drone over the sandstone — the aerial work that separates her reel from phone-only creators.' },
  { file: '65C725B9-1FEB-4E21-A24F-3AAA1BEDDD6E.MP4', slug: 'desert-aerial', brand: null,
    title: 'Aerial over the valley', cat: 'tourism',
    desc: 'A drone push down the highway with the mesas stacked behind it.' },
  { file: 'Fossil Hills Park.mp4', slug: 'fossil-hills-park', brand: 'Fossil Hills Park',
    title: 'Fossil Hills Park', cat: 'tourism',
    desc: 'Shade sails, slides and open sky — a park piece cut for parents deciding where to spend the morning.' },
  { file: 'Videoshop_2025-07-11_14-47-10-393.MOV', slug: 'playground-afternoon', brand: null,
    title: 'Playground afternoon', cat: 'tourism',
    desc: 'Colour-blocked play surfaces under sail shades, shot low and bright.' },
  { file: 'Videoshop_2025-07-07_16-53-45-889.MOV', slug: 'reservoir-red-rock', brand: null,
    title: 'Water in the desert', cat: 'tourism',
    desc: 'Red rock breaking to open water — the shot that explains why people move here.' },
  { file: 'Videoshop_2025-02-02_15-17-04-916.MOV', slug: 'desert-dog', brand: null,
    title: 'Desert morning', cat: 'tourism',
    desc: 'A dog picking a line across the slickrock. Lifestyle filler that cuts into almost anything.' },

  // --- Restaurants & food ---
  { file: 'Sandtown Pizza.MOV', slug: 'sandtown-pizza', brand: 'Sandtown Pizza',
    title: 'Sandtown Pizza', cat: 'food',
    desc: 'Menu board, room tone, and the food shot honestly — 4K, downtown on Bluff Street.' },
  { file: 'ADB20C90-2919-477F-831F-DE9997FB5AEE.MP4', slug: 'mac-bar', brand: null,
    title: 'Mac bar counter', cat: 'food',
    desc: 'Warm counter light and a menu overhead, shot to feel like walking in at lunch.' },
  { file: 'Lemon Lab Reel W Music.mp4', slug: 'lemon-lab', brand: 'Lemon Lab',
    title: 'Lemon Lab', cat: 'food',
    desc: 'Fresh lemonade poured over gingham at 60fps — slowed just enough to hold the pour.' },
  { file: 'Paletas.MP4', slug: 'paletas', brand: null,
    title: 'Paletas, dipped to order', cat: 'food',
    desc: 'The chocolate dip in one unbroken take. Process shots like this outperform the finished-product photo.' },
  { file: '89A602B5-606C-42B7-9299-B5A4C7A55C24.MP4', slug: 'mini-pies', brand: null,
    title: 'Mini pies, boxed', cat: 'food',
    desc: 'Labelled lids lined up on the board — a bakery flat-lay with the branding kept legible.' },

  // --- Beauty & wellness ---
  { file: '729EA322-0EC5-4981-B04F-4B8625CB1EFF.MP4', slug: 'microneedling', brand: null,
    title: 'Treatment, explained', cat: 'beauty',
    desc: 'A med-spa procedure filmed close with captions carrying the explanation — educational content that answers the question before it is asked.' },
  { file: '1E7856B6-1983-4A2E-81CC-4F1DE1B9F2C6.MP4', slug: 'treatment-room', brand: null,
    title: 'In the treatment room', cat: 'beauty',
    desc: 'Seventy seconds start to finish, gloved and unhurried, so a nervous first-timer knows exactly what to expect.' },
  { file: 'E3DCEB3F-9F5A-4CBE-A7D8-5BECDA19DEA2.MP4', slug: 'mapping-detail', brand: null,
    title: 'Mapping the work', cat: 'beauty',
    desc: 'Ink lines drawn on skin before the procedure — the prep step most brands never think to film.' },
  { file: '6B6952EC-DECB-47E8-A2A4-0770F5929D6C.MP4', slug: 'fitting-room', brand: null,
    title: 'A careful fitting', cat: 'beauty',
    desc: 'A specialist fitting appointment handled gently on camera, shot for a subject that needs warmth over polish.' },
  { file: 'Reel W No Captions.MP4', slug: 'prenatal-session', brand: null,
    title: 'Prenatal session', cat: 'beauty',
    desc: 'Hands-on work through a birth-ball session — delivered clean, with no captions, for the client to caption themselves.' },
  { file: 'Reel w music.MP4', slug: 'quiet-hands', brand: null,
    title: 'Close work', cat: 'beauty',
    desc: 'A detail piece cut to music — hands working small, kept in tight the whole way through.' },

  // --- Family brands ---
  { file: 'D422FCDA-B9CA-4F60-890F-5EBC792406A9.MP4', slug: 'toydash', brand: 'ToyDash',
    title: 'ToyDash', cat: 'family',
    desc: 'Screen-recorded pick-and-rank flow cut against real play — an app walkthrough aimed squarely at parents.' },
  { file: 'Hawaii Fluid Art.mp4', slug: 'hawaii-fluid-art', brand: 'Hawaii Fluid Art',
    title: 'Hawaii Fluid Art', cat: 'family',
    desc: 'Poured paint spreading in real time. A studio activity that sells itself if you just hold the shot.' },
  { file: '8A09F9BC-A942-4396-B39B-22BF2E6CBC1A.MP4', slug: 'showroom-visit', brand: null,
    title: 'A good day in the showroom', cat: 'family',
    desc: 'Customers, a gift box, a room mid-celebration — the human moment rather than the product.' },

  // --- Events & hospitality ---
  { file: '99D5284C-BC5E-49F0-B56B-02ACB3B7F31D.MP4', slug: 'audio-guestbook', brand: null,
    title: 'Audio guestbook', cat: 'events',
    desc: 'A vintage handset on a whiskey barrel, waiting for messages. Event rental content that shows the piece in situ.' },
  { file: '312CC4F8-15E1-42A5-BE36-8DC8B20ACF95.MP4', slug: 'stage-performance', brand: null,
    title: 'Stage night', cat: 'events',
    desc: 'Low-light stage footage held steady through a full number — the hardest condition to shoot clean.' },
  { file: '0910C4EB-9ADE-4CFA-AEBA-951BE0C209A2.MP4', slug: 'pageant-night', brand: null,
    title: 'Pageant night', cat: 'events',
    desc: 'Sash, crown and the hug straight after. Shot fast, outdoors, with no second take available.' },
];

export const SKIP = ['89A602B5-606C-42B7-9299-B5A4C7A55C24 2.MP4']; // byte-identical dupe of the above
